### ISSUE TITLE
How to Get Selected Text in Rich Text Editor?

### ISSUE THREAD

**Issue by SauloSA** [weweb-assets/ww-input-rich-text#46]
Please

I need help with rich text, and despite posting my question in the community, I haven't received a response and haven't found a solution in any other forum threads either. 

I need help with interacting with selected text within the rich text editor on the WeWeb platform. What I want is for the user to be able to select a fragment of the text and then send that fragment to ChatGPT.

Could someone guide me on how to implement this functionality? I am looking for the best way to capture the text selection and send the selected content to an integration with ChatGPT.

Here is an image example of what I am looking to achieve:

![image](https://github.com/user-attachments/assets/6b4e7d98-68ac-478c-8860-bba7c3682666)

Topic: https://community.weweb.io/t/how-to-get-selected-text-in-rich-text-editor/9905

**Comment by alexyca** [comment]
Answers have been given in [Topic](https://community.weweb.io/t/how-to-get-selected-text-in-rich-text-editor/9905)
